server:
  port: 8888
  
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
     server:
       git:
         default-label: master
         uri: https://github.com/LiamJDesmond84/Spring-Cloud-Config-Server
         #clone-on-start: true
    
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    instance:
#      hostname: localhost